### ISSUE TITLE
archci.com is not accessable

### ISSUE THREAD

**Issue by yikaus** [ArchCI/archci#10]
URL is not accessable .

https://www.site24x7.com/public/t/results-1435618637462.html . 

Is that only accessable from China ?

Kevin

**Comment by tobegit3hub** [comment]
Thanks for your attention @yikaus 

We will re-open the website until Arch 0.2.0 releases. Then everyone can access the public CI services. Currently Arch 0.1 just works for our local development environment. Please wait and we will come back soon :smiley:

**Comment by tobegit3hub** [comment]
Now we have the stable server to run public ArchCI service. Please go to http://archci.com/ :smile:
