### ISSUE TITLE
guideline for setting up the development environment

### ISSUE THREAD

**Issue by larrycai** [ArchCI/archci#11]
it is so simple in README that it can't be followed to setup the environment (redis/postgresql..). 

In slides, command `docker run -v $PWD:/project golang:1.4 /project/archci.sh > docker.log 2>&1` doesn't work

It will be nice list those dependence can be written in step-wise guideline first, then it can be automated into script or Dockerfile. refer to #1 

Thanks.

**Comment by tobegit3hub** [comment]
Great. That's really important for the project and community. We will add it soon :smiley:

**Comment by tobegit3hub** [comment]
Now we have better document in http://archci.com:8000 and the [archci/demo](https://github.com/ArchCI/demo) container to run ArchCI service.
