### ISSUE TITLE
Not able to remove project ? 

### ISSUE THREAD

**Issue by yikaus** [ArchCI/archci#28]
Hi 

Correct me if wrong , not see any place I can remove the project .

Kevin

**Comment by tobegit3hub** [comment]
Embarrassing, you're right. We should only remove the projects which are created by us. Now the login/logout part is incomplete. If you're using for private projects, we can implement this API first but it's not safe for public service.

**Comment by tobegit3hub** [comment]
I will implement this at this weekend. Everyone is welcome for discussion and implementation :smiley:

**Comment by yikaus** [comment]
Deleting project works , but builds not get cleaned when project removed  .

**Comment by tobegit3hub** [comment]
Nice catch @yikaus . It's related to https://github.com/ArchCI/archci/issues/29 that we're working on.
